export enum ApiPaths {
  SEARCH_RESULT = 'search/',
  SEARCH_PRODUCTS = 'eshop-items/?search=',
  CATEGORIES = 'categories',
  UPDATE_USER_INFO = 'users/update/profile/',
  GET_USER_INFO = 'users/profile/',
  GET_ORDER_HISTORY_DETAILS = 'eshop-order/details/',
  GET_CANCELLATION_REASONS = 'orders/complainlist/',
  POST_CANCELLED_ORDER = 'eshop-order/order-cancel/',
  PLACE_ORDER = 'eshop-order/place-order/',
  ITEM_REQUEST = 'request-items/',
  ORDER_HISTORY = 'eshop-order/list/',
  DIGITAL_PAYMENT_VALIDATION = 'eshop-order/digitalpayment/validation/',
  DIGITAL_PAYMENT_REINITIATE = 'eshop-order/digitalpayment/reinitiate/',
  ORDER_TACKING = 'eshop-order/list/',
  // HOME_GROUP_PRODUCTS = 'eshop-items/home-group/',
  HOME_GROUPS = 'eshop-items/home-group/',
  POST_RATING_REVIEW = 'items/rating-review/',
  IPDC_PRODUCTS = 'eshop-items/?ipdc=1',
  VOUCHER = 'voucher/',
  ORDER_REVIEW = 'eshop-order/order-rating/',
  JS_CODE = 'external-code/',
  BKASH_PAYMENT_VALIDATION = 'bkash/bkash-payment-validation/',
  BKASH_PAYMENT_REINITIATE = 'bkash/bkash-payment-reinitiate/'
}
